module.exports = {
  game_status: {
    IN_PROGRESS: 'in_progress',
    COMPLETED: 'completed',
  },
  card_rank: {
    1: '1',
    2: '2',
    3: '3',
    4: '4',
    5: '5',
    6: '6',
    7: '7',
    8: '8',
    9: '9',
    10: '10',
    11: '11',
    12: '12',
    13: '13',
  },
  card_suit: {
    CLUBS: 'clubs',
    HEARTS: 'hearts',
    DIAMONDS: 'diamonds',
    SPADES: 'spades',
  },
  card_values: {
    one: '1',
    two: '2',
    three: '3',
    four: '4',
    five: '5',
    six: '6',
    seven: '7',
    eight: '8',
    nine: '9',
    ten: '10',
    eleven: '11',
  },
};
